
### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "securePassword123",
  "firstName": "John",
  "lastName": "Doe",
  "role": "CUSTOMER"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "customer@example.com",
  "password": "securePassword123"
}
